# Generated by Django 3.1 on 2021-03-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accr', models.CharField(max_length=10)),
                ('satellite', models.CharField(choices=[('S1', 'Sentinel-1'), ('S2', 'Sentinel-2'), ('S3', 'Sentinel-3')], default=None, max_length=2)),
                ('band_1', models.BooleanField(default=False)),
                ('band_2', models.BooleanField(default=False)),
                ('band_3', models.BooleanField(default=False)),
                ('band_4', models.BooleanField(default=False)),
                ('band_5', models.BooleanField(default=False)),
                ('band_6', models.BooleanField(default=False)),
                ('band_7', models.BooleanField(default=False)),
                ('band_8', models.BooleanField(default=False)),
                ('band_9', models.BooleanField(default=False)),
                ('band_10', models.BooleanField(default=False)),
                ('band_11', models.BooleanField(default=False)),
                ('band_12', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('index', models.ManyToManyField(blank=True, to='api.Indice')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
