# Generated by Django 3.1 on 2021-03-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accr', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='index',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='band_1',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='band_10',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='band_11',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='band_12',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='band_2',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='band_3',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='band_4',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='band_5',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='band_6',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='band_7',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='band_8',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='band_9',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='satellite',
        ),
        migrations.AddField(
            model_name='indice',
            name='satellite_to_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.satellite'),
        ),
    ]
