# Generated by Django 3.1 on 2021-03-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210312_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='operator',
            field=models.CharField(default='European Space Agency', max_length=255),
        ),
    ]
