# Generated by Django 3.1 on 2021-03-12 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210312_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='indice_to_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.indice'),
        ),
    ]
