# Generated by Django 3.1 on 2021-03-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_application_indice_to_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=255)),
                ('wavelength', models.IntegerField(default='0', help_text='Central wavelength (nm)', max_length=4)),
                ('resolution', models.IntegerField(default='0', help_text='Spatial resolution (m)', max_length=4)),
                ('satellite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.satellite')),
            ],
        ),
    ]
