# Generated by Django 3.1 on 2021-03-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bands',
            name='resolution',
            field=models.DecimalField(decimal_places=0, default='0', help_text='Spatial resolution (m)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='bands',
            name='wavelength',
            field=models.DecimalField(decimal_places=0, default='0', help_text='Central wavelength (nm)', max_digits=4),
        ),
    ]
