# Generated by Django 3.1 on 2021-03-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210312_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bands',
            new_name='Band',
        ),
    ]
