# Generated by Django 3.1 on 2021-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210312_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='satellite',
            new_name='in_satellite',
        ),
        migrations.AddField(
            model_name='satellite',
            name='used_bands',
            field=models.ManyToManyField(to='api.Band'),
        ),
    ]
