# Generated by Django 3.1 on 2021-03-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210312_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='used_bands',
        ),
    ]
