# Generated by Django 3.1 on 2021-03-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_satellite_used_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='indice',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
