# Generated by Django 3.1 on 2021-03-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_indice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='indice',
            name='needed_bands',
            field=models.ManyToManyField(to='api.Band'),
        ),
    ]
