# Generated by Django 3.1 on 2021-03-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_indice_needed_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='task',
            field=models.CharField(choices=[('SAR', 'sar'), ('MSI', 'msi')], default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
