# Generated by Django 3.1 on 2021-03-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210318_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='indice',
            name='calc',
            field=models.CharField(blank=True, help_text='Use calculation just for if normalized difference is checked!', max_length=255),
        ),
        migrations.AddField(
            model_name='indice',
            name='is_nd',
            field=models.BooleanField(blank=True, default=0, help_text='Is this indice a normalized difference?'),
            preserve_default=False,
        ),
    ]
