# Generated by Django 3.1 on 2021-03-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210318_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indice',
            old_name='is_nd',
            new_name='is_NormalizedDifference',
        ),
    ]
