# Generated by Django 3.1 on 2021-03-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210318_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ma_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
