# Generated by Django 3.1 on 2021-03-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210319_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='machine_name',
            field=models.SlugField(allow_unicode=True, max_length=255),
        ),
    ]
